version: '2'
networks:
  app-network:
    driver: bridge
services:
  redis:
    image: docker.io/bitnami/redis:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
    networks:
      - app-network
  dispatcher:
    build:
      context: ../
      dockerfile: DispatcherDockerfile
    networks:
      - app-network
  db:
    container_name: postgres_db
    image: postgres:latest
    restart: always
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    ports:
        - '5432:5432'
    volumes: 
        - db:/var/lib/postgresql/data
    networks:
      - app-network
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - app-network
volumes:
  redis_data:
    driver: local
  db:
    driver: local