version: '2'
networks:
  app-network:
    driver: bridge
services:
  redis:
    image: docker.io/bitnami/redis:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
    networks:
      - app-network
  dispatcher:
    build:
      context: ../
      dockerfile: DispatcherDockerfile
    networks:
      - app-network
volumes:
  redis_data:
    driver: local